# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheCoffeeStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheCoffeeStore
    pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'Alamofire'
  pod 'SDWebImage', '~> 5.0'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  target 'TheCoffeeStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheCoffeeStoreUITests' do
    # Pods for testing
  end

end
